[package]
name = "async-fs-utils-attr-impl"
version = "0.1.0"
edition = "2021"
authors = ["Axel Lord"]
license = "MIT OR Apache-2.0"

[dependencies]
proc-macro2 = "1.0.86"
syn = { version = "2.0.79", features = ["full", "extra-traits"] }
quote = "1.0.37"

[lints]
workspace = true
